<?php
/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/compute/v1/compute.proto
 * Updates to the above are reflected here through a refresh process.
 */

namespace Google\Cloud\Compute\V1\InsertFirewallPolicyRequest;

/**
 * Wrapper class for the oneof _parent_id defined in message
 * InsertFirewallPolicyRequest. Only one item should be set on an instance of this
 * class. If multiple items are set on the instance, the last one is used.
 */
class ParentIdOneof
{
    /**
     * The value for the field parent_id, if set.
     */
    private $parentId;

    /**
     * Name of the field for which the oneof is set, as it appears in the protobuf in
     * lower_camel_case.
     */
    private $selectedOneofFieldName = '';

    /**
     * Sets this oneof to parent_id and updates its value.
     *
     * @param string $parentId The new value of this oneof.
     *
     * @return ParentIdOneof The modified object.
     */
    public function setParentId($parentId)
    {
        $this->parentId = $parentId;
        $this->selectedOneofFieldName = 'parent_id';
        return $this;
    }

    /**
     * Returns true if this oneof is set to the field parent_id.
     *
     * @return bool
     */
    public function isParentId()
    {
        return $this->selectedOneofFieldName === 'parent_id';
    }

    /**
     * Returns parentId if this oneof is set to the field parent_id, null otherwise.
     *
     * @return string|null
     */
    public function getParentId()
    {
        return $this->isParentId() ? $this->parentId : null;
    }
}
